CREATE TABLE UsuarioSQL (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Usuario NVARCHAR(100) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    Nombre NVARCHAR(200) NOT NULL,
    Rol NVARCHAR(50) NOT NULL DEFAULT 'Usuario',
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL
);